# Generated by Django 4.1.7 on 2023-04-17 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_listes_alter_todos_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="todos",
            name="liste",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="todos",
                to="todos.listes",
            ),
            preserve_default=False,
        ),
    ]
