# Generated by Django 4.1.7 on 2023-04-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0003_todos_liste"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listes",
            name="list_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
